#!/usr/bin/env python3
"""writes resources/icon.svg. run `node scripts/make-icon.mjs` afterwards for the png.

the body follows apple's icon grid: an 824px squircle centred on a 1024 canvas, with the soft
shadow macOS icons carry. a full-bleed icon looks oversized in the Dock next to everything else.
"""
import math
import pathlib

BODY = "#1F1E1D"  # --color-canvas, dark
GROUND = 716


def squircle(cx, cy, r, n=5.0, steps=240):
    # apple's shape has continuous curvature. a superellipse with n=5 is the usual close match,
    # and a plain rounded rect is visibly not it.
    pts = []
    for i in range(steps):
        t = 2 * math.pi * i / steps
        c, s = math.cos(t), math.sin(t)
        x = cx + r * (abs(c) ** (2 / n)) * (1 if c >= 0 else -1)
        y = cy + r * (abs(s) ** (2 / n)) * (1 if s >= 0 else -1)
        pts.append(f"{x:.1f} {y:.1f}")
    return "M" + " L".join(pts) + "Z"


def tree(x, top, r, colour):
    # the outline in the body colour keeps overlapping canopies apart without a second colour
    return (
        f'<g stroke="{BODY}" stroke-width="18" paint-order="stroke">'
        f'<rect x="{x - 15}" y="{top}" width="30" height="{GROUND - top}" rx="15" fill="{colour}" stroke="none"/>'
        f'<circle cx="{x}" cy="{top}" r="{r}" fill="{colour}"/></g>'
    )


body = squircle(512, 512, 412)
svg = f"""<!-- a grove: three trees, and each one is also a commit on a stem - a worktree.
     flat on purpose, like the app. generated by scripts/make-icon-svg.py - edit that, not this. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">
  <defs>
    <filter id="shadow" x="-10%" y="-10%" width="120%" height="125%">
      <feDropShadow dx="0" dy="12" stdDeviation="14" flood-color="#000" flood-opacity="0.32"/>
    </filter>
    <clipPath id="clip"><path d="{body}"/></clipPath>
  </defs>
  <path d="{body}" fill="{BODY}" filter="url(#shadow)"/>
  <g clip-path="url(#clip)">
    <!-- the rim is what keeps a dark icon's shape on a dark Dock -->
    <path d="{body}" fill="none" stroke="#FFFFFF" stroke-opacity="0.13" stroke-width="6"/>
    <g transform="translate(512 548) scale(1.14) translate(-512 -548)">
      <rect x="262" y="{GROUND - 7}" width="500" height="14" rx="7" fill="#F5F4EF" fill-opacity="0.16"/>
      {tree(676, 520, 84, "#8F8D86")}
      {tree(352, 468, 100, "#CFCDC3")}
      {tree(520, 372, 132, "#D97757")}
    </g>
  </g>
</svg>
"""
out = pathlib.Path(__file__).resolve().parent.parent / "resources" / "icon.svg"
out.write_text(svg)
print(out)
