import { mkdir, readFile } from "node:fs/promises";
import path from "node:path";
import { writeFileAtomic } from "../fsx.ts";
import type { Combo, LongWorkMode } from "../types.ts";

export const DEFAULT_LONG_WORK: LongWorkMode = "background";

export function longWorkMode(combo: Pick<Combo, "longWork">): LongWorkMode {
  return combo.longWork === "foreground" ? "foreground" : DEFAULT_LONG_WORK;
}

export function longWorkPolicyPath(combo: Pick<Combo, "root">): string {
  return path.join(combo.root, ".claude", "long-work.md");
}

/** the policy itself, in the words both the file and a single session's override use */
function policyBody(mode: LongWorkMode): string[] {
  const tail = ["", "The person can overrule this for any single task just by saying so."];
  if (mode === "foreground") {
    return [
      "# Long work: in this conversation",
      "",
      "Do long work yourself, here, in the foreground. Do not hand it to the `long-task` agent.",
      ...tail,
    ];
  }
  return [
    "# Long work: in the background",
    "",
    "Hand anything you expect to take more than a few minutes of autonomous work to the `long-task`",
    "agent. It always runs in the background, so this conversation stays free to answer questions and",
    "plan the next thing while it works.",
    "",
    "- it cannot see this conversation. write the plan to `plans/` first, and give it that file's path plus any constraint the plan leaves out",
    "- one agent per independent piece of work. say which working copy and which files each one owns",
    "- when it reports back, check its work before saying it is done",
    ...tail,
  ];
}

/**
 * CLAUDE.md is read once, when a session starts, so a switch written there could never change a
 * session that is already running. this file is different: the stub tells claude to read it each
 * time, right before long work begins. flipping it takes effect on the next long task, mid-session.
 */
export function renderLongWorkPolicy(mode: LongWorkMode): string {
  return [
    "<!-- generated by Grove. switch it in the app, or with the editor command",
    '     "Grove: Toggle Background Long Work". edits here are overwritten. -->',
    "",
    ...policyBody(mode),
    "",
  ].join("\n");
}

/**
 * the policy for one session, whatever the combo says. it rides on `--append-system-prompt`, so
 * the note about the file is left out, and it says why it wins over the file.
 */
export function longWorkSessionPolicy(mode: LongWorkMode): string {
  return [
    ...policyBody(mode),
    "",
    "This is set for this session only. It overrides .claude/long-work.md, which is the combo's default for other sessions.",
  ].join("\n");
}

/**
 * the same override where nothing but the prompt gets in (the VS Code panel): one plain line the
 * person sees, and can change, before sending
 */
export function longWorkPromptLine(mode: LongWorkMode): string {
  return mode === "foreground"
    ? "For this session, do long work here in the conversation, not with the long-task agent."
    : "For this session, hand long work to the long-task agent in the background, with the plan in plans/ first.";
}

/** writes the policy for the combo's current mode. untouched when it already says the right thing. */
export async function syncLongWorkPolicy(
  combo: Combo,
): Promise<{ path: string; changed: boolean }> {
  const file = longWorkPolicyPath(combo);
  const want = renderLongWorkPolicy(longWorkMode(combo));
  try {
    if ((await readFile(file, "utf8")) === want) return { path: file, changed: false };
  } catch {
    // not written yet
  }
  await mkdir(path.dirname(file), { recursive: true });
  await writeFileAtomic(file, want);
  return { path: file, changed: true };
}
