// what grove 0.10 installed into a project for the record, taken out again. the record was cards,
// questions and conclusions that agents wrote through an MCP server grove ran. 0.11 dropped it,
// and a project left as 0.10 made it points every session at a launcher that is gone and tells it
// to use tools it does not have.
//
// only what grove wrote goes. cards/, conclusions/ and .claude/grove-project.json are the
// person's, and so is every key and line grove did not write. the status hooks (`# grove-status`)
// stay: they are where the inbox comes from. every step can run again and change nothing.
import { readFile, rm, rmdir, stat } from "node:fs/promises";
import path from "node:path";
import { isObject, readJsonGuarded, stringifyLike, writeFileAtomic } from "../fsx.ts";
import { getStateDir } from "../paths.ts";
import { projectIdOf } from "../project/ids.ts";
import { type HookSyncStatus, syncComboStatusHooks } from "../sessions/liveStatus.ts";
import type { Combo, Warning } from "../types.ts";

const SERVER = "grove";
/** on the record's SessionStart hook */
const HOOK_MARKER = "# grove-record";
/** the launcher 0.10 pointed a project at: <appRoot>/.grove/bin/record */
const LAUNCHER = /\/\.grove\/bin\/record$/;
const LAUNCHER_RULE = /^Bash\(.*\/\.grove\/bin\/record:\*\)$/;
const RULES_FILE = path.join(".claude", "rules", "grove-record.md");
const RULES_HEADER =
  "<!-- generated by Grove from the record's tool list. edits here are overwritten. -->";

const isRecordHook = (group: unknown) =>
  isObject(group) &&
  Array.isArray(group.hooks) &&
  group.hooks.some(
    (h) => isObject(h) && typeof h.command === "string" && h.command.includes(HOOK_MARKER),
  );

/**
 * a parsed settings.local.json without the record's keys: its hook, the launcher's allow rule,
 * and the server's name and tool rule. `keepServer` when the project's .mcp.json still has a
 * server called grove that is not grove's: then its name and its rule are the person's too
 */
export function withoutRecord(
  root: Record<string, unknown>,
  keepServer = false,
): Record<string, unknown> {
  const next = { ...root };
  if (isObject(root.hooks)) {
    const hooks: Record<string, unknown> = {};
    for (const [event, groups] of Object.entries(root.hooks)) {
      if (!Array.isArray(groups)) {
        hooks[event] = groups;
        continue;
      }
      const kept = groups.filter((g) => !isRecordHook(g));
      // an event left with nothing was only ever grove's
      if (kept.length > 0 || groups.length === 0) hooks[event] = kept;
    }
    next.hooks = hooks;
  }
  const enabled = root.enabledMcpjsonServers;
  if (!keepServer && Array.isArray(enabled) && enabled.includes(SERVER)) {
    const kept = enabled.filter((s) => s !== SERVER);
    if (kept.length) next.enabledMcpjsonServers = kept;
    else delete next.enabledMcpjsonServers;
  }
  const perms = root.permissions;
  if (isObject(perms) && Array.isArray(perms.allow)) {
    const allow = perms.allow.filter(
      (r) =>
        !(
          typeof r === "string" &&
          (LAUNCHER_RULE.test(r) || (!keepServer && r === `mcp__${SERVER}`))
        ),
    );
    if (allow.length !== perms.allow.length) {
      const { allow: _, ...rest } = perms;
      if (allow.length) next.permissions = { ...perms, allow };
      else if (Object.keys(rest).length) next.permissions = rest;
      else delete next.permissions;
    }
  }
  return next;
}

/** the `grove` server in <root>/.mcp.json, and whether it is the one grove added */
async function groveServer(root: string) {
  const file = path.join(root, ".mcp.json");
  const read = await readJsonGuarded(file);
  if (read.status !== "ok" || !isObject(read.value) || !isObject(read.value.mcpServers)) {
    return undefined;
  }
  const { [SERVER]: entry, ...servers } = read.value.mcpServers;
  if (entry === undefined) return undefined;
  const ours = isObject(entry) && typeof entry.command === "string" && LAUNCHER.test(entry.command);
  return { file, text: read.text, json: read.value, servers, ours };
}

/**
 * <root>/.mcp.json without the server grove added. grove owned `mcpServers.grove` and nothing
 * else in it. a server by that name that runs something else is the person's, and stays
 */
async function cleanMcpJson(root: string): Promise<boolean> {
  const found = await groveServer(root);
  if (!found?.ours) return false;
  const next = { ...found.json, mcpServers: found.servers };
  // grove made the file when there was none. with nothing else in it, it goes the way it came
  if (Object.keys(next).length === 1 && Object.keys(found.servers).length === 0) {
    await rm(found.file);
  } else await writeFileAtomic(found.file, stringifyLike(next, found.text));
  return true;
}

/** the rules file, which grove rewrote on every sync, and its folder when nothing else is in it */
async function removeRules(root: string): Promise<boolean> {
  const file = path.join(root, RULES_FILE);
  const text = await readFile(file, "utf8").catch(() => null);
  if (!text?.startsWith(RULES_HEADER)) return false;
  await rm(file);
  await rmdir(path.dirname(file)).catch(() => {});
  return true;
}

/**
 * what 0.10 wrote once into a new project, and what 0.9 and 0.11 write in its place. a file is
 * the person's from the moment it is made, so a line is only swapped where it is still exactly
 * the one grove wrote
 */
const CLAUDE_MD: ReadonlyArray<readonly [string, string]> = [
  [
    [
      "agents, other tabs. They do not share your conversation. The project record is the memory you",
      "have in common: cards (who is doing what), questions with their answers, and conclusions",
      "(decisions, findings, verdicts). `.claude/rules/grove-record.md` says how to read and write it.",
      "",
      "- before starting a task, call `record_state`, and claim a card before you work on it",
      "- record each decision, finding and verdict when it is settled, yours and the person's",
      "- `context/` is for longer notes the record points at: `context/<topic>.md`, short dated entries, added to and never rewritten",
    ].join("\n"),
    [
      "agents, other tabs. They do not share your conversation. The files in `context/` are the only",
      "memory you have in common.",
      "",
      "- before starting a task, read `context/`",
      "- when you decide something, learn something non-obvious, or finish a piece of work, write it to `context/<topic>.md` as a short dated entry",
      "- add to a file, do not rewrite it. another session may be reading it or adding to it",
      "- before a large edit in a working copy, say what you are touching in `context/in-progress.md`, and remove your entry when done. two sessions editing the same files is what this prevents",
    ].join("\n"),
  ],
];
const LONG_TASK: ReadonlyArray<readonly [string, string]> = [
  [
    "- call `record_state`. work under the card your brief names. the session that started you holds it. do not claim, release or finish a card yourself (the rules' Subagents section says the same)",
    "- add an entry to `context/in-progress.md` naming the working copy and the files you will touch",
  ],
  [
    '- when you decide something the plan did not settle, find something out, or judge an approach, record it with `conclusion_record` and pass `as: "long-task"`. a question you would have asked goes on the card with `question_ask`, with what you assumed',
    "- when you decide something the plan did not settle, or learn something non-obvious, add a short dated entry to `context/<topic>.md`",
  ],
  [
    "- put your report on the card with `comment_add`, and list what you made in `artifacts`. the session that started you marks the card done",
    "- remove your entry from `context/in-progress.md`",
  ],
];

async function swapLines(
  file: string,
  swaps: ReadonlyArray<readonly [string, string]>,
): Promise<boolean> {
  const text = await readFile(file, "utf8").catch(() => null);
  if (text === null) return false;
  let next = text;
  for (const [from, to] of swaps) next = next.replace(from, () => to);
  if (next === text) return false;
  // the person's file: never half written, and with the mode they gave it
  await writeFileAtomic(file, next, (await stat(file)).mode & 0o777);
  return true;
}

/**
 * every file of a project but its settings.local.json, which the status hooks share (see
 * syncComboSettings). returns what it changed, as paths from the project root
 */
export async function cleanRecordFiles(combo: Combo): Promise<string[]> {
  const cleaned: string[] = [];
  if (await cleanMcpJson(combo.root)) cleaned.push(".mcp.json");
  if (await removeRules(combo.root)) cleaned.push(RULES_FILE);
  if (await swapLines(path.join(combo.root, "CLAUDE.md"), CLAUDE_MD)) cleaned.push("CLAUDE.md");
  const agent = path.join(".claude", "agents", "long-task.md");
  if (await swapLines(path.join(combo.root, agent), LONG_TASK)) cleaned.push(agent);
  return cleaned;
}

/**
 * the status hooks, and with `cleanRecord` the record's keys out, in one read and one write of
 * the project's settings.local.json. a session that was running through the upgrade writes the
 * copy it loaded at startup back over this, record and all, so the app runs it again whenever
 * the file changes
 */
export async function syncComboSettings(
  appRoot: string,
  combo: Combo,
  cleanRecord: boolean,
): Promise<{ status: HookSyncStatus; warning?: Warning }> {
  if (!cleanRecord) return syncComboStatusHooks(appRoot, combo);
  // after cleanRecordFiles, a server called grove that is still there is the person's
  const theirs = (await groveServer(combo.root)) !== undefined;
  return syncComboStatusHooks(appRoot, combo, (settings) => withoutRecord(settings, theirs));
}

/** <appRoot>/.grove/bin/record and record.cjs: the launcher and the server no project runs any more */
export async function removeRecordRuntime(appRoot: string): Promise<string[]> {
  const dir = path.join(getStateDir(appRoot), "bin");
  const removed: string[] = [];
  for (const name of ["record", "record.cjs"]) {
    const file = path.join(dir, name);
    if (
      await rm(file).then(
        () => true,
        () => false,
      )
    ) {
      removed.push(file);
    }
  }
  if (removed.length) await rmdir(dir).catch(() => {});
  return removed;
}

/**
 * 0.10 filed what the person dismissed under each project's card prefix. the prefix went with the
 * record, so those marks move under the project's id: this is each prefix and the id that takes
 * its place. the prefix is in combos.json, else in the project file 0.10 left in the folder.
 *
 * a prefix that is another project's id is left out: its keys cannot be told from that project's
 * own. the marks under it stay where they are, and what they dismissed comes back once
 */
export async function recordPrefixes(combos: readonly Combo[]): Promise<Map<string, string>> {
  const ids = new Set(combos.map(projectIdOf));
  const out = new Map<string, string>();
  for (const c of combos) {
    // 0.10 read a hand-written one upper-cased, and filed under that
    let prefix: unknown = typeof c.prefix === "string" ? c.prefix.toUpperCase() : undefined;
    if (typeof prefix !== "string") {
      const file = await readJsonGuarded(path.join(c.root, ".claude", "grove-project.json"));
      prefix = file.status === "ok" && isObject(file.value) ? file.value.prefix : undefined;
    }
    const id = projectIdOf(c);
    if (typeof prefix === "string" && prefix && prefix !== id && !ids.has(prefix)) {
      out.set(prefix, id);
    }
  }
  return out;
}
