import { mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import {
  longWorkMode,
  longWorkPolicyPath,
  longWorkPromptLine,
  longWorkSessionPolicy,
  renderLongWorkPolicy,
  syncLongWorkPolicy,
} from "../../src/combos/longWork.ts";
import { prepareComboOpen } from "../../src/combos/prepare.ts";
import { normalizeCombosFile } from "../../src/combos/schema.ts";
import type { Combo } from "../../src/types.ts";
import { makeSandbox } from "../helpers/transcript.ts";

function combo(over: Partial<Combo> = {}): Combo {
  const root = path.join(makeSandbox("grove-longwork-"), "claude-ws", "prod-debug");
  mkdirSync(root, { recursive: true });
  return { name: "prod-debug", root, folders: [], ...over };
}

describe("where long work runs", () => {
  it("background unless the combo says otherwise", () => {
    expect(longWorkMode({})).toBe("background");
    expect(longWorkMode({ longWork: "foreground" })).toBe("foreground");
    const { combos } = normalizeCombosFile(
      {
        combos: [
          { name: "a", folders: [], longWork: "foreground" },
          { name: "b", folders: [], longWork: "sideways" },
        ],
      },
      "/ws",
    );
    expect(combos.map((c) => c.longWork)).toEqual(["foreground", undefined]);
  });

  it("the two policies say opposite things about the long-task agent, and both can be overruled", () => {
    const bg = renderLongWorkPolicy("background");
    const fg = renderLongWorkPolicy("foreground");
    expect(bg).toContain("to the `long-task`");
    expect(bg).toContain("write the plan to `plans/` first");
    expect(fg).toContain("Do not hand it to the `long-task` agent");
    for (const policy of [bg, fg]) {
      expect(policy).toContain("overrule this for any single task");
      expect(policy).toContain("generated by Grove");
    }
  });

  it("one session's override is the file's policy, without the note about the file, and says it wins", () => {
    for (const mode of ["background", "foreground"] as const) {
      const file = renderLongWorkPolicy(mode);
      const session = longWorkSessionPolicy(mode);
      expect(session).not.toContain("generated by Grove");
      expect(session).not.toContain("<!--");
      // every line of the policy itself is there, word for word
      const policy = file.split("\n").slice(3).join("\n").trim();
      expect(session.startsWith(policy)).toBe(true);
      expect(session).toMatch(/overrides \.claude\/long-work\.md/);
      expect(session).toContain("this session only");
    }
    expect(longWorkSessionPolicy("foreground")).toContain(
      "Do not hand it to the `long-task` agent",
    );
    expect(longWorkSessionPolicy("background")).toContain("to the `long-task`");
  });

  it("the one-line form for the editor's prompt box says which way, in plain words", () => {
    expect(longWorkPromptLine("foreground")).toBe(
      "For this session, do long work here in the conversation, not with the long-task agent.",
    );
    expect(longWorkPromptLine("background")).toMatch(
      /^For this session, hand long work to the long-task agent/,
    );
    for (const mode of ["background", "foreground"] as const) {
      expect(longWorkPromptLine(mode)).not.toContain("\n");
    }
  });

  it("flipping the combo rewrites the file, and an unchanged policy is not rewritten", async () => {
    const c = combo();
    expect(await syncLongWorkPolicy(c)).toMatchObject({ changed: true });
    const file = longWorkPolicyPath(c);
    expect(file).toBe(path.join(c.root, ".claude", "long-work.md"));
    expect(readFileSync(file, "utf8")).toBe(renderLongWorkPolicy("background"));

    const before = statSync(file).mtimeMs;
    await new Promise((r) => setTimeout(r, 15));
    expect((await syncLongWorkPolicy(c)).changed).toBe(false);
    expect(statSync(file).mtimeMs).toBe(before);

    // the switch a running session sees: same file, other policy
    expect((await syncLongWorkPolicy({ ...c, longWork: "foreground" })).changed).toBe(true);
    expect(readFileSync(file, "utf8")).toBe(renderLongWorkPolicy("foreground"));
  });

  it("a hand edit is put back: the file belongs to the switch, not to the person", async () => {
    const c = combo();
    await syncLongWorkPolicy(c);
    writeFileSync(longWorkPolicyPath(c), "something else\n");
    expect((await syncLongWorkPolicy(c)).changed).toBe(true);
    expect(readFileSync(longWorkPolicyPath(c), "utf8")).toBe(renderLongWorkPolicy("background"));
  });

  it("opening a combo leaves the policy in step with combos.json", async () => {
    const c = combo({ longWork: "foreground" });
    await prepareComboOpen(path.dirname(c.root), c);
    expect(readFileSync(longWorkPolicyPath(c), "utf8")).toBe(renderLongWorkPolicy("foreground"));
  });
});
