import { describe, expect, it } from "vitest";
import { cleanBlockText, extractCommand, extractUserText } from "../../src/transcript/prompt.ts";
import { text, userEntry } from "../helpers/transcript.ts";

describe("the system-reminder block trap", () => {
  // written first on purpose. the verified real-world shape: injected blocks first, typed text last.
  const trap = userEntry([
    text("<system-reminder>The user's computer can be reached...</system-reminder>"),
    text("<system-reminder>The user's timezone is...</system-reminder>"),
    text("are there any tools or ides etc where i can create different groups of project"),
  ]);

  it("reminder blocks first, typed text last -> typed text", () => {
    expect(extractUserText(trap)).toBe(
      "are there any tools or ides etc where i can create different groups of project",
    );
  });

  it("joining the blocks first and testing the result would lose the prompt", () => {
    const blocks = (trap.message.content as Array<{ text: string }>).map((b) => b.text);
    // a naive "does the joined turn start with '<'" check calls this whole turn machinery
    expect(blocks.join("\n").startsWith("<")).toBe(true);
    expect(blocks.map(cleanBlockText).filter(Boolean)).toEqual([blocks[2]]);
  });

  it("a reminder and the typed text inside one block", () => {
    const e = userEntry([text("<system-reminder>injected</system-reminder>\nfix the flaky test")]);
    expect(extractUserText(e)).toBe("fix the flaky test");
  });

  it("a trailing reminder is stripped", () => {
    const e = userEntry([text("fix the flaky test\n<system-reminder>injected</system-reminder>")]);
    expect(extractUserText(e)).toBe("fix the flaky test");
  });

  it("a prompt that mentions the tag in prose survives byte-identical", () => {
    const prose =
      "Injected `<system-reminder>` blocks come first. strip `<system-reminder>...</system-reminder>` spans, then read on";
    expect(extractUserText(userEntry([text(prose)]))).toBe(prose);
    expect(extractUserText(userEntry(prose))).toBe(prose);
  });

  it("an unclosed reminder is machinery", () => {
    expect(cleanBlockText("<system-reminder>never closed")).toBeNull();
  });
});

describe("what really precedes typed text in 2.1.x", () => {
  it("<ide_opened_file> block first -> typed text", () => {
    const e = userEntry([
      text(
        "<ide_opened_file>The user opened the file /Users/you/src/api/app.rb in the IDE.</ide_opened_file>",
      ),
      text("can you look into fixing this issue?"),
    ]);
    expect(extractUserText(e)).toBe("can you look into fixing this issue?");
  });

  it("<ide_selection> block first -> typed text", () => {
    const e = userEntry([text("<ide_selection>lines 1-3</ide_selection>"), text("explain this")]);
    expect(extractUserText(e)).toBe("explain this");
  });
});

describe("content shapes", () => {
  it("bare string content handled", () => {
    expect(extractUserText(userEntry("just a string prompt"))).toBe("just a string prompt");
  });

  it("slash-command envelope as string content is not a prompt, but yields a command", () => {
    const e = userEntry(
      "<command-name>/mcp</command-name>\n<command-message>mcp</command-message>\n<command-args>list</command-args>",
    );
    expect(extractUserText(e)).toBeUndefined();
    expect(extractCommand(e)).toBe("/mcp list");
  });

  it("command without args", () => {
    expect(extractCommand(userEntry("<command-name>clear</command-name>"))).toBe("/clear");
  });

  it("Caveat: and [Request interrupted blocks are dropped", () => {
    expect(cleanBlockText("Caveat: The messages below were generated by the user")).toBeNull();
    expect(cleanBlockText("[Request interrupted by user]")).toBeNull();
  });

  it("several surviving blocks are joined", () => {
    expect(extractUserText(userEntry([text("one"), text("<x>no</x>"), text("two")]))).toBe(
      "one\ntwo",
    );
  });

  it("missing or odd shapes never throw", () => {
    for (const e of [
      null,
      1,
      "x",
      {},
      { type: "user" },
      { type: "user", message: 3 },
      { type: "user", message: { content: 7 } },
      { type: "user", message: { content: [null, 3, {}] } },
    ]) {
      expect(extractUserText(e)).toBeUndefined();
      expect(extractCommand(e)).toBeUndefined();
    }
  });
});

describe("entries that are not a person's turn", () => {
  const cases: Array<[string, Record<string, unknown>]> = [
    ["isSidechain", { isSidechain: true }],
    ["isMeta", { isMeta: true }],
    ["isCompactSummary", { isCompactSummary: true }],
    ["toolUseResult", { toolUseResult: { stdout: "" } }],
    ["task-notification origin", { origin: { kind: "task-notification" } }],
  ];
  for (const [name, extra] of cases) {
    it(`${name} -> skipped`, () => {
      expect(extractUserText(userEntry([text("looks like a prompt")], extra))).toBeUndefined();
    });
  }

  it("a tool_result block -> skipped", () => {
    const e = userEntry([{ type: "tool_result", tool_use_id: "t", content: "ok" }, text("hm")]);
    expect(extractUserText(e)).toBeUndefined();
  });

  it("origin.kind human is a real turn", () => {
    expect(extractUserText(userEntry([text("hi")], { origin: { kind: "human" } }))).toBe("hi");
  });
});
