// the texts agents read, generated from the registry so they cannot name a tool that does not
// exist: the rules file grove writes into each combo, the server instructions, and the CLI help.
import { TOOLS } from "./tools.ts";
import { usage } from "./validate.ts";
import { SERVER_NAME } from "./version.ts";

export const RULES_FILE = ".claude/rules/grove-record.md";

function shellQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

/** a path as an agent should type it: bare when the shell sees nothing special in it, which is what the Bash(<launcher>:*) rule was measured with, quoted otherwise. */
function shellWord(s: string): string {
  return /^[A-Za-z0-9_/.,:@%+=-]+$/.test(s) ? s : shellQuote(s);
}

export interface RulesInput {
  /** absolute path of the launcher, as it goes into the Bash fallback. */
  launcher: string;
  /** the project's card prefix, so the examples use this project's ids. */
  prefix: string;
  /** the combo root. the fallback passes it, so it works from any folder. */
  root: string;
}

/** the whole of <combo>/.claude/rules/grove-record.md. */
export function renderRules({ launcher, prefix, root }: RulesInput): string {
  const P = prefix || "AUTH";
  const rec = shellWord(launcher);
  const at = `--root ${shellWord(root)}`;
  const tools = TOOLS.filter((t) => t.mcp !== false).map((t) => `- \`${t.name}\` - ${t.summary}`);
  return `<!-- generated by Grove from the record's tool list. edits here are overwritten. -->

# The project record

One person runs this whole project, across many sessions. They read the record - cards,
questions and conclusions - not your transcript. Other agents, including ones that start after
you, work from the same record. What is not in it, nobody else knows.

You read and write it through the \`mcp__grove__*\` tools. Never create or edit a file under
\`cards/\` or \`conclusions/\` yourself: ids and claims are only safe through the tools, and two
agents writing by hand end up with the same id. Reading those files is fine.

The record replaces \`context/in-progress.md\`. Where CLAUDE.md or an agent file tells you to
write there, claim a card instead. \`context/\` and \`plans/\` stay, for long notes and plans:
name the file in a card, a comment or a conclusion.

## Every session

- before you start work: \`record_state\`. A subagent, and a session started inside a working
  copy, is not shown the state at session start, so for them this call is the only way to see it
- at the start of each turn, and after a resume or a fork: \`my_cards\`
- when the person's message decides, picks, approves or corrects anything, even with a bare
  "8h" or "go ahead", record it with \`conclusion_record\` (\`by: "person"\`) before you act on it
- if two "you:" lines in your context disagree, the newest one is right

## Cards

A card is one sizeable piece of work, not a small task.

- \`card_claim\` a card before you work on it. One session holds a card. If another agent holds
  it, do not work on it. If you are told its holder's process is gone, ask the person. Only
  call \`card_takeover\` when they say so
- when your card is finished, pick up the unclaimed card closest to what you were doing. When
  nothing related is left, tell the person
- \`card_create\` when you find work that is not part of your card. Do not do that work yourself
  unless it is small and blocks you
- \`card_done\` when the card is complete, saying what was done and what was not.
  \`card_release\` to give it back unfinished. \`card_cancel\` when it should not be done
- \`comment_add\` when you made something (a branch, a PR, a file in \`artifacts/\`), learned
  something the next agent would otherwise have to find out again, or stopped early

## Conclusions: decisions, findings, verdicts

Call \`conclusion_record\` whenever something is settled after thinking it over or looking into
it, by you or by the person. Do it at that moment, not at the end.

- decision - what we will do: "refresh tokens stay on the server"
- finding - what turned out to be true: "staging has no okta tenant in terraform state"
- verdict - a judgement on an option, an approach or a piece of work: "the saml strategy
  cannot be reused for oidc", "option B is not worth the cost"

Explicit ones:

- you chose between real options (decision)
- you investigated something and reached an answer (finding)
- you judged whether something is safe, good enough or worth it (verdict)
- the person told you how to do it, picked an option, answered your question, approved your
  plan or gave a judgement. "sounds good", "go with that", "no, use redis", "8h, to match the
  policy" and "that's not worth it" are all conclusions, and they are the person's:
  \`by: "person"\`. \`by: "agent"\` is only for what you reached yourself

Implicit ones, the kind nobody announces:

- you picked a default, a limit, a timeout, a name, a file layout or the shape of an API (decision)
- you picked a library, a tool or a pattern over another (decision)
- you took something as true without checking it (finding - say in \`why\` that it is unchecked)
- you ruled an approach out and moved on (verdict)
- you left something out of scope, or did less than the card says (decision)
- you changed something another card or conclusion depends on (decision, with \`related\`)

The test: would an agent picking this up tomorrow need to know it, to avoid undoing it or
working it out again? Then record it. Do not record routine edits, what the diff already says,
thinking that led nowhere, or that a card is finished (that is \`card_done\`).

One conclusion per thing settled. A value, the approach and an option you ruled out are three
conclusions, so a later one can replace one of them without hiding the others.

Before you settle something, call \`conclusion_search\`. If it is already settled, follow it and
cite its id. To go against it, record a new one with \`replaces\`, say why, and tell the person.
Set \`changes_plan\` on a finding the person has to see.

## Questions

Every question goes on a card with \`question_ask\`, and its answer goes there with
\`question_answer\`. A question that only lives in the chat is lost to everyone else.

- a question for the person: ask it on your card, then ask it in the chat too. If you cannot
  carry on without the answer, stop. If you can, say what you assume and carry on
- a value or a behaviour the person would want a say in that nobody gave you (a timeout, a
  limit, a price, words users see): pick one, record it as your decision, ask the person with
  \`question_ask\` and carry on with your pick. Do not mark the card done while that question
  is open: the card is waiting on them
- when the person answers, in the chat or anywhere else: \`question_answer\` with
  \`by: "person"\`. If the answer settles something it is also a conclusion, and it is theirs
- a question for another agent: \`question_ask\` with \`to\` set to that agent's card. They see
  it in \`my_cards\`, and you see their answer in yours
- \`my_cards\` lists the questions other agents left for you. Answer them

## Ids

A card is \`${P}-7\`, a comment or question on it \`${P}-7#3\`, a conclusion \`D-12\` (decision),
\`F-4\` (finding) or \`V-2\` (verdict). Write the id whenever you mention one, in card bodies,
comments, summaries and commit messages. That is how the person and other agents get from one
to the other.

## Subagents

If another agent started you, you share its session and its cards. Call \`record_state\` first.
Pass \`as\` with a short name of your own on every write. Put conclusions, comments and
questions on the card your brief names. Do not claim, release or finish a card unless the
brief says to. You cannot ask the person: put the question on the card with \`question_ask\`,
say what you assumed and carry on.

When you start a subagent, its brief may be all it reads: an Explore agent does not load this
file. Write into the brief the card id, that it calls \`record_state\` first, passes \`as\` on
every write and records what it finds on that card.

## If the tools are missing

With no \`mcp__grove__*\` tools, run the same tool through Bash. The arguments are ONE
single-quoted JSON argument:

    ${rec} call card_claim '{"card":"${P}-3"}' ${at}
    ${rec} call conclusion_record '{"kind":"finding","what":"...","why":"...","card":"${P}-3","by":"agent"}' ${at}
    ${rec} state ${at}

Write a \`'\` inside the JSON as \`'\\''\`. Do not use a heredoc, it is refused. \`${rec} tools\`
lists every tool with its arguments, and \`${rec} doctor ${at}\` says what is wrong. If that fails
too, tell the person "the Grove record is unavailable, open Grove once", and carry on without
writing record files by hand.

After a tool call that failed or was cut off, look first (\`card_show\`, \`record_state\`) and
only then retry: the write may have landed.

## The tools

${tools.join("\n")}
`;
}

/** sent in the MCP initialize result. claude code cuts it at 2,048 characters. kept under 600. */
export function renderInstructions(): string {
  return [
    "This server is the project's shared record: cards, questions and conclusions (decisions, findings, verdicts).",
    "The person running the project reads it instead of your transcript, and so does every other agent.",
    "Call record_state before you start work and my_cards at the start of each turn.",
    "Claim a card with card_claim before you work on it.",
    "Record each decision, finding and verdict with conclusion_record when it is settled, the person's included.",
    "Write only through these tools, never by hand under cards/ or conclusions/.",
    "Rules: .claude/rules/grove-record.md",
  ].join(" ");
}

export const EXIT_HELP =
  "exit: 0 ok. 1 bad arguments. 2 no such card or conclusion. 3 held by another agent. 4 the holder's process is gone. 5 you do not hold it. 6 the card is done or canceled. 7 takeover refused. 8 the record is unavailable.";

export function renderCliHelp(): string {
  return `record - the Grove project record

  record mcp                                   the stdio MCP server. the root comes from GROVE_RECORD_ROOT
  record state [--hook] [--all] [--root <dir>] print the project state. --hook never fails: on any error it prints one line and exits 0
  record call <tool> '<json>' [--root <dir>]   run one tool. the arguments are one JSON object. "-" reads it from stdin
  record tools                                 list the tools with their arguments
  record doctor [--root <dir>]                 check the launcher, the bundle, the runtime, the root and who you are

the root is --root, else $GROVE_RECORD_ROOT, else the nearest folder above the current one that holds .claude/grove-project.json.
${EXIT_HELP}
`;
}

/** `record tools`: one block per tool. */
export function renderToolList(): string {
  return `${TOOLS.map(
    (t) =>
      `${t.name}${t.mcp === false ? "  (CLI and library only)" : ""}\n  ${t.summary}\n  ${usage(t.name, t.input)}`,
  ).join("\n\n")}\n`;
}

// ---------- what grove writes into a combo besides the rules file. core's recordSync merges these ----------

/** the marker that makes a hook group grove-record's. not "# grove-status": the 0.3.0 extension strips groups with that marker. */
export const HOOK_MARKER = "# grove-record";

/** the one entry grove owns in <combo>/.mcp.json, under mcpServers.grove. no server-level alwaysLoad: the core tools carry it in their _meta. */
export function mcpServerEntry({ launcher, root }: { launcher: string; root: string }): {
  command: string;
  args: string[];
  env: Record<string, string>;
} {
  return { command: launcher, args: ["mcp"], env: { GROVE_RECORD_ROOT: root } };
}

/** the SessionStart hook command. sync (no async key), so its stdout reaches the model before the first prompt. */
export function hookCommand({ launcher, root }: { launcher: string; root: string }): string {
  return `${shellQuote(launcher)} state --hook --root ${shellQuote(root)} ${HOOK_MARKER}`;
}

/** the hook group grove owns in settings.local.json hooks.SessionStart. no matcher key: the form verified in a vs code tab. */
export function hookGroup(o: { launcher: string; root: string }): {
  hooks: { type: "command"; command: string; timeout: number }[];
} {
  return { hooks: [{ type: "command", command: hookCommand(o), timeout: 10 }] };
}

/**
 * <appRoot>/.grove/bin/record. its text depends only on the two paths, so it changes only when the
 * app moves: a freshly written launcher costs 300-400ms on its first run, a fresh bundle nothing.
 * `exec` keeps claude as the server's parent. GROVE_RECORD_BIN lets a server whose bundle was
 * replaced run its calls through this file. a hook gets its failure on stdout with exit 0, so the
 * model sees it (decision 11). anything else gets it on stderr with exit 8.
 */
export function renderLauncher({ execPath, bundle }: { execPath: string; bundle: string }): string {
  return `#!/bin/sh
# written by Grove. runs the project record with Grove's own runtime. edits here are overwritten.
G=${shellQuote(execPath)}
J=${shellQuote(bundle)}
GROVE_RECORD_BIN=$0
export GROVE_RECORD_BIN
if [ ! -f "$J" ]; then
  m="the record bundle is missing at $J"
elif [ -x "$G" ]; then
  ELECTRON_RUN_AS_NODE=1
  export ELECTRON_RUN_AS_NODE
  exec "$G" "$J" "$@"
elif node -e 'process.exit(+process.versions.node.split(".")[0] < 22 ? 1 : 0)' 2>/dev/null; then
  exec node "$J" "$@"
else
  m="Grove is not at $G and there is no node 22 or newer on PATH"
fi
case " $* " in *" --hook "*) echo "record unavailable: $m. open Grove once"; exit 0 ;; esac
echo "record unavailable: $m. open Grove once" >&2
exit 8
`;
}

/** the permissions.allow entries grove owns: every grove tool, and the CLI fallback through Bash. */
export function allowRules(launcher: string): string[] {
  return [`mcp__${SERVER_NAME}`, `Bash(${launcher}:*)`];
}

/** a Bash allow rule for a grove launcher at any path. core removes the ones that are not allowRules(current)[1]. */
export function isLauncherAllowRule(rule: string): boolean {
  return /^Bash\(.*\/\.grove\/bin\/record:\*\)$/.test(rule);
}
